### ISSUE TITLE
Aseprite makepkg error

### ISSUE THREAD

**Issue by Joilnen** [ImperatorStorm/PKGBUILDs#13]
I got this when try to compile aseprite 
``
/usr/local/include/fmt/core.h:2788:(.text._ZN3app3App21updateDisplayTitleBarEv+0x83): undefined reference to `fmt::v10::vformat[abi:cxx11](fmt::v10::basic_string_view<char>, fmt::v10::basic_format_args<fmt::v10::basic_format_context<fmt::v10::appender, char> >)'
/sbin/ld: /tmp/lto-llvm-06665d.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v10::format<char const*>(fmt::v10::basic_format_string<char, fmt::v10::type_identity<char const*>::type>, char const*&&)':
/usr/local/include/fmt/core.h:2788:(.text._ZN3app18PreviewCliDelegate8showHelpERKNS_10AppOptionsE+0x40): undefined reference to `fmt::v10::vformat[abi:cxx11](fmt::v10::basic_string_view<char>, fmt::v10::basic_format_args<fmt::v10::basic_format_context<fmt::v10::appender, char> >)'
/sbin/ld: /tmp/lto-llvm-06665d.o:/usr/local/include/fmt/core.h:2788: more undefined references to `fmt::v10::vformat[abi:cxx11](fmt::v10::basic_string_view<char>, fmt::v10::basic_format_args<fmt::v10::basic_format_context<fmt::v10::appender, char> >)' follow
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
``

**Comment by ImperatorStorm** [comment]
Cannot reproduce, have you tried https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot?
