### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by Ribiveer** [ImperatorStorm/PKGBUILDs#6]
I recently noticed that the Lua scripting functionality wasn't available in the version of Aseprite built using this PKGBUILD. Looking at it, I found this line:
https://github.com/ImperatorStorm/PKGBUILDs/blob/a626498ef09df577e3021c6137c9ae0c737f2d64/aseprite/PKGBUILD#L96
This line sets the environment variables for enabling the updater, Lua scripting and websocket functionality in said Lua scripting to NO. At first I chalked this up to personal choices -- some people might prefer not to have an updater after all -- even if I don't understand why anyone would remove extremely useful functionality like scripting. But if that were the case, wouldn't the variable be set to OFF like the other environment variables that represent toggles? This leads me to believe this was intended to be ON, rather than NO. The CMakeLists.txt files specifies the environment variables to be ON and OFF, after all:
https://github.com/aseprite/aseprite/blob/1366a6948cc765492c281a365a769b342f44e1c7/CMakeLists.txt#L62
I am not quite sure whether this is indeed a typo, or if it's really intended, but I figured it couldn't hurt opening up an issue to make sure that those two letters shouldn't be switched :P

**Comment by ImperatorStorm** [comment]
I'll take a look at it.

**Comment by Ribiveer** [comment]
Thank you!

**Comment by ImperatorStorm** [comment]
does it work with https://github.com/ImperatorStorm/PKGBUILDs/commit/c427a15da077fb6d744065aa6b68f9cf34c97c34?

**Comment by Ribiveer** [comment]
I incidentally made the same change on line 96 locally right after my last comment (but before yours) and it did indeed enable scripting!

**Comment by Ribiveer** [comment]
Thank you so much for the lightning-quick response and fix by the way! I really appreciate it
