### ISSUE TITLE
AVX Build Errors

### ISSUE THREAD

**Issue by blipk** [ImperatorStorm/PKGBUILDs#7]
Hey I'm getting a lot of the following errors when building from your Aseprite AUR.

```
[490/833] compile ../src/core/SkTypeface_remote.cpp
In file included from ../src/core/SkGlyph.h:16,
                 from ../src/core/SkScalerContext.h:20,
                 from ../src/core/SkDescriptor.h:18,
                 from ../src/core/SkScalerCache.h:16,
                 from ../src/core/SkTypeface_remote.cpp:10:
../include/private/SkVx.h: In instantiation of ‘skvx::VExt<N, T> skvx::to_vext(const Vec<N, T>&) [with int N = 4; T = long unsigned int; VExt<N, T> = __vector(4) long unsigned int]’:
../include/private/SkVx.h:284:84:   required from ‘skvx::Vec<N, T> skvx::operator>>(const Vec<N, T>&, int) [with int N = 4; T = long unsigned int]’
../include/private/SkVx.h:750:79:   required from here
../include/private/SkVx.h:253:20: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]
  253 |     SINT VExt<N,T> to_vext(const Vec<N,T>& v) { return bit_pun<VExt<N,T>>(v); }
      |                    ^~~~~~~
[491/833] compile ../src/core/SkYUVMath.cpp
```

It still seems to run fine for the most part, but crashes at times, and also the window menu gets displaced offscreen when minimizing/maximizing.

Not sure if the crashes are related to the AVX errors form the build?

If it's Aseprite issues I'll report on their repo instead.

Thanks.

**Comment by ImperatorStorm** [comment]
Warnings are not compile errors, and are something that should be reported to upstream.

Try [building `aseprite` in a clean chroot](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot); if the crashes and other issues still occur report them to upstream, as I don't think any of my patches _should_ be introducing issues.
