### ISSUE TITLE
Missing dependency on libsbsms in tenacity

### ISSUE THREAD

**Issue by tux314159** [ImperatorStorm/PKGBUILDs#8]
Hi, the package tenacity-wxgtk3-git now depends on libsbsms (it didn't use to I think), but this hasn't been added to the dependency list, so I got ```tenacity: error while loading shared libraries: libsbsms.so.2: cannot open shared object file: No such file or directory```. This was fixed by manually installing libsbsms from the arch repos.

**Comment by FabioLolix** [comment]
@ImperatorStorm you have decreased the pkgrel instead of incrementing it, you need to bring that to 4 otherwise no one will update

**Comment by ImperatorStorm** [comment]
Fixed
